config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :providers

  resources :cities

  devise_for :users
  resources :products

  root 'institutional#index'

  get '/proveedores' => 'system#provedor'

  get '/mostrar_provedor/:id' => 'system#mostrar_provedor', as: :mostrar_provedor

  resources :system

end

app/models/city.rb
class City < ActiveRecord::Base
	has_many :users
end

app/controllers/cities_controller.rb
# encoding: utf-8
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /citie
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to cities_url, notice: 'Ciudad sido creado con éxito' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to cities_url, notice: 'Ciudad se ha actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'Ciudad fue destruida con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:city)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ciudad %><br>
    <%= f.text_field :city,:class => "form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= f.submit "Guardar",:class => "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<%= render 'layouts/menu_lateral_admin' %>
<legend>Editar Ciudade</legend>
<%= render 'form' %>
<%= render 'layouts/footer_user' %>

app/views/cities/index.html.erb
<%= render 'layouts/menu_lateral_admin' %>
<legend>Ciudades</legend>


<%= link_to 'Nueva ciudad', new_city_path,:class => "btn btn-success btn-block" %>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Ciudade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destruir', city, method: :delete, data: { confirm: 'Estás seguro ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= render 'layouts/footer_user' %>

app/views/cities/new.html.erb
<%= render 'layouts/menu_lateral_admin' %>
<legend>Nueva Ciudad</legend>
<%= render 'form' %>
<%= render 'layouts/footer_user' %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @city.city %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>