config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :providers

  resources :cities

  devise_for :users
  resources :products

  root 'institutional#index'

  get '/proveedores' => 'system#provedor'

  get '/mostrar_provedor/:id' => 'system#mostrar_provedor', as: :mostrar_provedor

  resources :system

end

app/views/layouts/_footer_user.html.erb
		</div>
	</div>
</div>

app/views/layouts/_menu_lateral_admin.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
          <div class="panel-heading">
          </div>
          <ul class="list-group">
            <%= link_to "<i class='fa fa-home'></i> Home".html_safe,system_index_path,:class => "list-group-item" %>
            <%= link_to "<i class='fa fa-list'></i> Productos".html_safe,products_path,:class => "list-group-item" %>
            <%= link_to "<i class='fa fa-map-marker'></i> Ciudades".html_safe,cities_path,:class => "list-group-item" %>
            <%= link_to "<i class='fa fa-users'></i> Proveedores".html_safe,proveedores_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>  
          </ul>
        </div>
      </div>
      <div class="col-md-9">        
        <div class="pull-right">
            <%= link_to "Volver", '#', onclick: "history.back()" %>
          </div>

app/views/layouts/_menu_lateral_user.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
          <div class="panel-heading">
          </div>
          <ul class="list-group">
            <%= link_to "<i class='fa fa-home'></i> Home".html_safe,system_index_path,:class => "list-group-item" %>
            <%= link_to "<i class='fa fa-list'></i> Productos".html_safe,providers_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-file-text-o'></i> Cotações".html_safe,cotacoes_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>
            <%# link_to "<i class='fa fa-home'></i> Home".html_safe,root_path,:class => "list-group-item" %>  
          </ul>
        </div>
      </div>
      <div class="col-md-9">        
        <div class="pull-right">
            <%= link_to "Voltar", '#', onclick: "history.back()" %>
          </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prices</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<body>
<div class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mario Application</a>
    </div>
    <div class="navbar-collapse collapse">
      <div class="navbar-right top-yellow btn-login">
        <% if current_user.present? %>
        <div class="top-color">  <%= current_user.email %> - RUC <%= current_user.ruc %> /   <%= link_to "Sair", destroy_user_session_path, :method => :delete %> </div> <%# link_to "Entrar".html_safe,new_user_session_path,:class => "btn btn-default" %>            
        <% elsif current_admin.present? %> 
         <div class="top-color">  <%= current_admin.email %> /  <%= link_to "Sair", destroy_admin_session_path, :method => :delete %>  </div>
        <% else %>
          <%= link_to "Entrar".html_safe,new_user_session_path,:class => "btn btn-default" %> 
        <% end %>
      </div>
    </div><!--/.nav-collapse -->
  </div>
</div>


<%= yield %>

</body>
</html>